apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: client
    spec:
      containers:
        - env:
            - name: CLIENT_PORTPORT
              value: "9000"
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: SERVER_PORT
              value: "3050"
          image: akwasnik/client:1.0.0
          name: client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
