version: '3.8'

services:

  client:
    build: ./client/.
    ports:
      - "${CLIENT_PORT}:80"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

  server:
    build: ./server/.
    ports:
      - "${SERVER_PORT}:3000"
    command: node app.js
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      retries: 5
      timeout: 5s



