version: '3.8'

services:

  client:
    build: ./client/.
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - app-net

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

  server:
    build: ./server/.
    ports:
      - "${SERVER_PORT}:3000"
    command: node app.js
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-net
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  app-net:
    driver: bridge

volumes:
  redis_data:
  db_data: