apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start-dev
            - --import-realm
            - --verbose
          env:
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /opt/keycloak/data/import/master-realm.json
          image: quay.io/keycloak/keycloak:26.1.4
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/master-realm.json
              name: keycloak-cm0
              readOnly: true
              subPath: master-realm.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: master-realm.json
                path: master-realm.json
            name: keycloak-cm0
          name: keycloak-cm0
