apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - node
            - app.js
          env:
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "3050"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_PORT
              value: "6379"
          image: akwasnik/server:1.0.0
          name: server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3050
              protocol: TCP
      restartPolicy: Always
